runtime: python38 # or another supported version

instance_class: F2

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  GOOGLE_CLOUD_PROJECT: "shoes-finder-project"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/images

- url: /static
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

